### ISSUE TITLE
Critcl compilation of tcllib-1.20 on tcl8.7a3 -> hanging with 100% cpu usage in TclBN_mp_copy etc

### ISSUE THREAD

**Issue by jheimone1** [andreas-kupries/critcl#107]
Hi,

it looks like there is a problem in either critcl or in the new tcl8.7 alpha. Basically,
compiling the critcl accelerated functions of tcllib-1.20 (make critcl) hang "forever" with 100% CPU utilization in functions like TclBN_mp_copy (see below). I was able to reproduce this with 2 different OS and gcc versions and 2 different hardware (both physical computers, i.e no virtualization involved).

The same operation works flawlessly with tcl8.5 and tcl8.6.10 so somehow it looks like it is a problem in tcl 8.7 or in the way how critcl and tcl8.7 work togther. Unfortunately, I don't have the skills to debug the root cause, but below are exact step-to-step instructions to reproduce the problem.

Should I also/instead report this to the tcl core developers as a potential tcl 8.7 problem?

br, Jorma Heimonen

Steps to reproduce:
0. Environment:

- CenTos 6 with devtoolset-8 
gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

- CenTos 7 with the build in gcc
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

1. Download https://prdownloads.sourceforge.net/tcl/tcl8.7a3-src.tar.gz and extract
2. Configure with
./configure --prefix=/opt/tcl8.7 --enable-64bit --enable-shared --disable-symbols --enable-man-symlinks --enable-64bit --disable-zipfs
3. Compile: make ; make install
4. Download tcllib-1.20 from https://core.tcl-lang.org/tcllib/uv/tcllib-1.20.tar.gz and extract
5. Configure and make install
./configure --prefix=/opt/tcl8.7; make install
6. Download the latest critcl 3.1.18.1 and extract (andreas-kupries-critcl-f7fdaa5)
7. Install
/opt/tcl8.7/bin/tclsh8.7 ./build.tcl install
8. Compile tcllib with critcl
cd tcllib-1.20
PATH=/opt/tcl8.7/bin:$PATH make critcl

Result: 

- tclsh8.7 takes 100% of CPU and hangs "forever" (It did not finish in an hour).

- perf top shows that functions TclBN_mp_copy, TclBN_mp_clear and 
TclBN_mp_mul_2d are taking excessive amounts of CPU

  49.88%  libtcl8.7.so                            [.] TclBN_mp_copy
  31.26%  libtcl8.7.so                            [.] TclBN_mp_clear
  12.49%  libtcl8.7.so                            [.] TclBN_mp_mul_2d

**Comment by andreas-kupries** [comment]
Thank you for the report.

At first thought I suspect that something is going into an infinite loop. Given the functions something involving very large numbers (They are what Tcl uses when it goes beyond 64 bit to arbitrary precision).

Do you see an initial output similar to

```
/home/aku/opt/ActiveTcl/bin/critcl -cache /home/aku/Play/Tcllib/dev/.critcl -force -libdir ./modules -pkg tcllibc ./modules/tcllibc.tcl ./modules/md4/md4c.tcl ./modules/struct/graph_c.tcl ./modules/base32/base32_c.tcl ./modules/struct/sets_c.tcl ./modules/json/jsonc.tcl ./modules/pt/pt_rdengine_c.tcl ./modules/pt/pt_parse_peg_c.tcl ./modules/uuid/uuid.tcl ./modules/struct/tree_c.tcl ./modules/base32/base32hex_c.tcl ./modules/base64/base64c.tcl ./modules/base64/uuencode.tcl ./modules/base64/yencode.tcl ./modules/sha1/sha1c.tcl ./modules/md5/md5c.tcl ./modules/crc/crcc.tcl ./modules/crc/sum.tcl ./modules/crc/crc32.tcl ./modules/md5crypt/md5cryptc.tcl ./modules/struct/queue_c.tcl ./modules/rc4/rc4c.tcl ./modules/sha1/sha256c.tcl ./modules/struct/stack_c.tcl ./modules/dns/ipMoreC.tcl
```

?

If yes then we should be able to dig a bit deeper which of the modules trigger the issue.
For background the `make critcl` is just a small shim over the `./sak.tcl critcl` command. And while a make target does not accept arguments, the underlying tool does.

IOW it is possible to run `./sak.tcl critcl /path/to/module` to invoke it on just that module.
all the `./modules/...` paths after the `-pkg` option in my example output above are the individual accelerators in Tcllib.

Using `sak.tcl` directly should allows us to figure out which of these all trigger the problem you have. 

I have to go to work now. Will continue on this when I am back home this evening. Thank you for your patience.

**Comment by andreas-kupries** [comment]
Ok. It seems that both `base64c` and `crcc` trigger this behaviour.
If you do not need these two packages/accelerators then you can work around the issue by opening the file

`tcllib-1.20/support/installation/version.tcl` and disabling the two lines
```
critcl      base64c      {base64/base64c.tcl base64/uuencode.tcl base64/yencode.tcl}
critcl      crcc         {crc/crcc.tcl crc/sum.tcl crc/crc32.tcl}
```
before doing `make critcl`.
(Disabling = Commenting or removing)

**Comment by andreas-kupries** [comment]
Running `critcl` directly the troublesome files seem to be `crc32.tcl` and `yencode.tcl`.

**Comment by andreas-kupries** [comment]
`yencode.tcl` does `package require crc32` and pulls in the trouble from `crc32.tcl` that way.

The `crc32.tcl` tries to compute a sign bit. It looks for integer wrap around. The code is

```
    # calculate the sign bit for the current platform.
    variable signbit
    if {![info exists signbit]} {
	variable v
        for {set v 1} {int($v) != 0} {set signbit $v; set v [expr {$v<<1}]} {}
        unset v
    }
```

Comparing 8.7 and 8.6 behaviour, and disabling the loop condition `int($v) !- 0` for 8.6 I suspect changes in the behaviour of the `int()` function for expressions. In 8.6 it limits the argument to 64 bit, while in 8.7 it allows the result to also be of arbitrary precision. This causes the loop to never find the wrap around it is looking for.

And as I thought, this change in behaviour has been TIPped.

See https://core.tcl-lang.org/tips/doc/trunk/tip/514.md

So, this is a Tcllib bug, where it has not been fully adapted to 8.7.

Oh, and this `signbit` goes into the Tcl implementation of the crc code, not used by the C side at all (Insult to injury).

Better way in the modern Tcl versions might be to look at the `tcl_platform(wordSize)`.

**Comment by andreas-kupries** [comment]
That said `(It did not finish in an hour).` ... Stress test for Tcl's arbitrary precision arithmetic. I wonder how big a number it managed to reach in this tight loop, and running an hour.

Currently running my fix for Tcllib through its test suite. Already confirmed that it works for my Tcl 8.7.

**Comment by andreas-kupries** [comment]
Note, I am not running the entire Tcllib testsuite against 8.7 yet. Only confirmed that the change fixes the generation of the accelerators. The full run above is still only against 8.[456]. Checking all of Tcllib against 8.7 is a bigger kettle of fish.

**Comment by andreas-kupries** [comment]
Tcllib fix is up on its trunk, see commit https://core.tcl-lang.org/tcllib/ci/7737acdb11cb8956?diff=0
