### ISSUE TITLE
Unable to build an RPM for the installation of critcl

### ISSUE THREAD

**Issue by erempel** [andreas-kupries/critcl#108]
To build an RPM using the RPM toolkit the install step must be able to install to an arbitrary location, and fortunately this can be done with the comand
tclsh build.tcl install /path/to/arbitrary/path/lib/tcl8.x
however, the resulting binary code has references to this location, which is incorrect.

In my particular case the command

tclsh build.tcl install /usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6

and the resulting callback.so has lots of reverences to this path

bash-4.4$ strings /usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6/critcl_callback1/linux-x86_64/callback.so | grep BUILD

No arguments left to use for extension (callback->nargs > 0), in file /usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c/callback.c @line 48
Too many arguments (objc <= callback->nargs), in file /usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c/callback.c @line 80
/usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6/critcl3.1.18/critcl_c/tcl8.5
/usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6/critcl3.1.18/critcl_c/tcl8.5
/usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c
/usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6/critcl3.1.18/critcl_c/tcl8.5
/usr/local/uvredhat/BUILD/critcl-3.1.18
/usr/local/uvredhat/BUILDROOT/critcl-3.1.18-0.el8.x86_64/usr/lib64/tcl8.6/critcl-cutil0.2/trace/trace.c
/usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c/callback.c

The md5c.so does not have this kind of path reference in it.

Is there a way to build install this package to an arbitrary location without referencing the installed location?

**Comment by andreas-kupries** [comment]
Both the callback and the md5 should be built in the same manner. As such I do not recall/know what the difference is. Starting to look into this.

**Comment by andreas-kupries** [comment]
Focusing on the

```
No arguments left to use for extension (callback->nargs > 0), in file /usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c/callback.c @line 48
Too many arguments (objc <= callback->nargs), in file /usr/local/uvredhat/BUILD/critcl-3.1.18/lib/critcl-callback/c/callback.c @line 80
```

lines, in my environment, after running

```
./build.tcl install ../XYZ |& tee LOG
strings ../XYZ/critcl_callback1/linux-x86_64/callback.so |grep argument
```

I see 
```
No arguments left to use for extension (callback->nargs > 0), in file %s @line %d
Too many arguments (objc <= callback->nargs), in file %s @line %d
```

So, I have `%s` and `%d` in the strings where you have the full path and line.

These strings come from
```
lib/critcl-callback/c/callback.c:48:    ASSERT (callback->nargs > 0, "No arguments left to use for extension");
lib/critcl-callback/c/callback.c:80:    ASSERT (objc <= callback->nargs, "Too many arguments");
```
in the sources.

The md5 sources do not have any ASSERTs, which may explain that the resulting .so does not have any references.

The `ASSERT` macro is defined in `lib/critcl-cutil/asserts/critcl_assert.h`. It essentially is

```
#define ASSERT(x,msg) if (!(x)) {                               \
        Tcl_Panic (msg " (" #x "), in file %s @line %d",        \
                   __FILE__, __LINE__);                         \
    }
```

I do not see how the %s and %d can be filled in at compile time. 

While the __FILE__ is likely a const string which would be put into the .so, it should be a separate element. Your output looks as if it was interpolated into the const format string before compilation. I wonder if your build system has some kind of pre/post processing on things like this.

As a first step, see what happens when you disable the command `critcl::cutil::assertions on` in the `callback.tcl` file before building.

**Comment by andreas-kupries** [comment]
I should disable the assertions by default also, I believe.

**Comment by andreas-kupries** [comment]
Ah! The second thing to disable in the sources (`callback.tcl`) is `critcl::debug symbols`.
This also puts path information into the generated .so

**Comment by andreas-kupries** [comment]
Done in 07292456bda518052c20fad66e40f217122ec478 (trunk).

@erempel I hope that helps. Please ping me with results when you have the time again to look at this.

**Comment by erempel** [comment]
Thanks. This now builds to an RPM with the rpmbuild toolkit.
