### ISSUE TITLE
::critcl::ScanCore in critcl.tcl error at comment lines

### ISSUE THREAD

**Issue by GeraldKi** [andreas-kupries/critcl#126]
The first line already generates an error.

```
gk@vm2004:~/bin/Cryptkit_build$ critcl -config ~/bin/Cryptkit_build/config.txt -pkg cryptkit
Config:   linux-x86_64-gcc
Build:    linux-x86_64-gcc
Target:   linux-x86_64
Source:   cryptkit.tcl can't read "cmd": no such variable
    while executing
"dict exists $config $cmd"
    (procedure "ScanCore" line 57)
...
```

```
gk@vm2004:~/bin/Cryptkit_build$ tclsh
% package require critcl
3.1.18
% ::critcl::ScanDependencies 1620 cryptkit.tcl
-1|﻿#   Cryptkit - a Tcl interface to the Cryptlib security toolkit|   <-- puts $lno|$line|
can't read "cmd": no such variable
```
$lno also counts somewhat unfamiliarly.

**Comment by andreas-kupries** [comment]
@GeraldKi  Please provide the `cryptkit.tcl` file triggering the error, or a suitably reduced form still triggering it without providing private and/or internal information.

**Comment by andreas-kupries** [comment]
Also, is the `-config ~/bin/Cryptkit_build/config.txt` a necessary part to induce the issue ?

**Comment by GeraldKi** [comment]
I no longer have this version and I can't reproduce the error either. close ticket.

**Comment by GeraldKi** [comment]
Oh yeah, I'm so bad at programming. I want to use SSH. My attempts to create cryptkit linux-x86_64 are now getting to the point where the connection is established. $channel puts “ls –l” (from the documentation) returns invalid command name "::crypt::puts". And there's more to come. Something must have gone wrong before then.
But that's not a critcl problem.
