### ISSUE TITLE
Documentation of passing String Arguments

### ISSUE THREAD

**Issue by rhcarvalho** [andreas-kupries/critcl#127]
CriTcl looks very interesting, thanks for maintaining and developing it further!

I was reading the documentation at [https://andreas-kupries.github.io/critcl/doc/files/critcl_howto_use.html](https://andreas-kupries.github.io/critcl/doc/files/critcl_howto_use.html#:~:text=printf(%22hello%20world%2C%20from%20%25s%20(%25d%20bytes)%5Cn%22%2C%20x)%3B), and I think if I understand it well then:

```diff
   critcl::cproc hello {char* x} void {
 	/* char* x; */
-	printf("hello world, from %s (%d bytes)\n", x);
+	printf("hello world, from %s\n", x);
     }
```

**Comment by andreas-kupries** [comment]
Thank you for the report.

Done with commit ac0c795e8bffb333146093caea35aef943c9c0e2
TODO: updating the site.
