### ISSUE TITLE
Documentation How To Tcl Runtime Version

### ISSUE THREAD

**Issue by rhcarvalho** [andreas-kupries/critcl#128]
In https://andreas-kupries.github.io/critcl/doc/files/critcl_howto_use.html#:~:text=and%20what%20version%20of%20the%20public%20Tcl%20API%20is%20available%20to%20the%20C%20coe.

```diff
- [...] and what version of the public Tcl API is available to the C coe.
+ [...] and what version of the public Tcl API is available to the C code.
```

**Comment by andreas-kupries** [comment]
Thank you for the report.

Done with commit ac0c795e8bffb333146093caea35aef943c9c0e2
TODO: updating the site.
