### ISSUE TITLE
Documentation Additional Tcl Code

### ISSUE THREAD

**Issue by rhcarvalho** [andreas-kupries/critcl#129]
https://andreas-kupries.github.io/critcl/doc/files/critcl_howto_use.html#:~:text=greetings%20hello-,greeting%20hi,-The%20Tcl%20builtin

```diff
     greetings hello
-    greeting hi
+    greetings hi
```

(I hope these small doc issues are not too distracting; sorry for the noise)

**Comment by andreas-kupries** [comment]
Not at all, and not really noise. Thank you for the report.

Done with commit ac0c795e8bffb333146093caea35aef943c9c0e2
TODO: updating the site.
