### ISSUE TITLE
Can't build critcl under Tcl 9

### ISSUE THREAD

**Issue by gromgit** [andreas-kupries/critcl#131]
Homebrew's [Tcl version bump](https://github.com/Homebrew/homebrew-core/pull/192020) dies when building critcl:
```
==> /usr/local/Cellar/tcl-tk/9.0.0/bin/tclsh build.tcl install
  version conflict for package "Tcl": have 9.0.0, need 8.6
      while executing
  "package require Tcl 8.6"
      (file "build.tcl" line 4)
```
Looks like `build.tcl` wasn't updated to:
```
package require Tcl 8.6 9
```

**Comment by gromgit** [comment]
Sorry, just noticed it's still building with an old version of critcl. Closing.

**Comment by andreas-kupries** [comment]
Even so, thank you for testing. :tada:
