### ISSUE TITLE
TEA build leaves a make file with empty targets

### ISSUE THREAD

**Issue by apnadkarni** [andreas-kupries/critcl#36]
Using the -tea option builds a tea package and the configure also runs without errors. However the generated makefile does nothing because the targets have no dependencies and there are no active rules in the makefile.

Tried with the latest release (3.1.9 - btw, the package require returns 3.1.8) on Linux (actually core.tcl.tk)

/Ashok

**Comment by andreas-kupries** [comment]
Can you provide a small example critcl package + the command lines (critcl, configure, make) used to reproduce the issue ?

**Comment by apnadkarni** [comment]
Dumb user error. I was typing `make` or `make all` and expecting a build but getting _Nothing to do for target all_. Did not realize one has to do `make install` to even just compile.

/Ashok

**Comment by andreas-kupries** [comment]
Do not sell yourself short here. The expectation of having 'make all' do something is fairly ingrained. I will review the generated Makefile. I should be able to at least generate a more suitable message.

Will have to see if I can get 'make all' do something sensible. Would be a bit more complicated. Issue is that 'critcl' is a one-in-all thing, i.e. it compiles and installs in one step.

**Comment by apnadkarni** [comment]
Not sure it is a big deal. Maybe the make all target can just print a message to that effect that nothing needs to be done.

 

/Ashok

**Comment by andreas-kupries** [comment]
'that nothing needs to be done'

Yes, that is what I meant by 'at least generate a more suitable message.'
