### ISSUE TITLE
build.tcl proc usage doesn't work on windows

### ISSUE THREAD

**Issue by pointsman** [andreas-kupries/critcl#42]
If build.tcl is called on windows cmd line without args or even with the arg "help" it raises error.

Reason is in the (in both cases called) proc usage. This proc looks, if ::errorInfo exists and if yes, if it is empty. If it is not empty, the proc bailes out with [exit]ing the script.

Unfortunately, on windows, errorInfo isn't emtpy, after interp startup, because of a catch in init.tcl (tcl_pkgPath doesn't exist on windows).

**Comment by andreas-kupries** [comment]
Ok, this is in critcl since 3.1.12, we are at 3.1.16, and no complaints were issued for 3 years. This is done. Closing.
