### ISSUE TITLE
critcl::reset for multiple compilations

### ISSUE THREAD

**Issue by tpoindex** [andreas-kupries/critcl#48]
Critcl currently only allows one compilation per program execution, here is an example:
```
$ tclsh8.6
% package require critcl
3.1.12
% critcl::cproc foo {} int {return 1;}
% foo
1
% critcl::cproc bar {} int {return 2;}
critcl::cproc (level 2 cmd {critcl::cproc bar {} int {return 2;}} line 1 type eval): Illegal attempt to define C code in  after it was built.
```
I propose a "critcl::reset" command be added, so that multiple compilations are supported.  I have a quick-and-dirty patch to do this.  The patch works by saving the critcl namespace variables and arrays, and restoring that state when critcl::reset is called.

```
*** critcl.tcl.orig	2014-11-20 11:35:19.115447013 -0700
--- critcl.tcl	2014-11-20 12:33:14.360826503 -0700
***************
*** 4847,4856 ****
--- 4847,4899 ----
      return
  }
  
+ proc ::critcl::InitialState {} {
+     variable _initialState
+     foreach _ns [concat [namespace current] [namespace children]] {
+         dict set _initialState $_ns [namespace eval $_ns {
+             set _arrays []
+             set _vars []
+             foreach _v [lsort [info vars]] {
+                 if {[regexp {^(_)|(arg)|(auto_)|(env)|(errorInfo)|(tcl_)|(history).*} $_v]} {
+                     continue
+                 }
+                 if {[array exists $_v]} {
+                     if {[catch {lappend _arrays $_v [array get $_v]}]} {
+                         lappend _arrays $_v {}
+                     }
+                 } else {
+                     if {[catch {lappend _vars   $_v [set $_v]}]} {
+                         lappend _vars $_v {}
+                     }
+                 }
+             }
+             list arrays $_arrays vars $_vars
+         }]
+     }
+     rename ::critcl::InitialState {}
+     return 
+ }
+ 
+ proc ::critcl::reset {} {
+     variable _initialState
+     foreach ns [concat [namespace current] [namespace children]] {
+         lassign [dict get $_initialState $ns] arrays arraydata vars vardata
+         foreach {_v _d} $arraydata {
+             unset ${ns}::$_v
+             array set ${ns}::$_v $_d
+         }
+         foreach {_v _d} $vardata {
+             set ${ns}::$_v $_d
+         }
+     }
+     return 
+ }
+ 
  # # ## ### ##### ######## ############# #####################
  ## State
  
  namespace eval ::critcl {
+     variable _initialState ;# state of package arrays/variables after initialization
      variable mydir    ;# Path of the critcl package directory.
      variable run      ;# interpreter to run commands, eval when, etc
  
***************
*** 5019,5024 ****
--- 5062,5068 ----
  
  	variable code	         ;# This array collects all code snippets and
  				  # data about them.
+         array set code {}
  
  	# Keys for 'code' (above) and their contents:
  	#
***************
*** 5206,5209 ****
--- 5250,5254 ----
  ## Ready
  
  ::critcl::Initialize
+ ::critcl::InitialState
  return

```

**Comment by andreas-kupries** [comment]
Ok, putting in the email thread about this feature, to have the larger record.
One comment per mail, either way.

**Comment by andreas-kupries** [comment]
And this works ?
I would have thought that the data about foo and bar is not present at
the initial state, so after the reset it would only know and build
code for baz ...

Note, this is only for the compile & run mode, right ?
Because when the file is precompiled with the critcl app ...

Actually, I think that might not be possible at the moment because the
invocation of foo, bar in the same code defining them very likely
break this as well. And this patch will be of no help with that.

I.e. this type of code will definitely prevent pre-building a package
you can use later.
It could only be made to work for compile&run ...

Why does your project need this interleaving of definitions and uses ?
Would it not be simpler to segregate them ?

> I don't want to assume that all cproc procedures are defined
> before any particular one is invoked.

How does work with package definition and use ?

Is your project strongly interactive where users dynamically enter the
definitions and uses in some type of console window ?

**Comment by andreas-kupries** [comment]
Side note:

https://core.tcl.tk/tcllib/doc/trunk/embedded/www/tcllib/files/modules/namespacex/namespacex.html#8

should simplify the code.

**Comment by andreas-kupries** [comment]
Yes, why not?  At the point of invoking "puts [foo]" (line 6 in my tests), both "foo" and "bar"
are compiled, loaded, and defined as Tcl commands.

After the two critcl::cproc commands (lines 4 and 5), the commands are neither compiled or defined,
but each are set in auto_index to compile:

% info commands foo
% info commands bar
% puts $auto_index(foo)
::critcl::cbuild {}
% puts $auto_index(bar)
::critcl::cbuild {}

Invoking either command causes the current buffer to be compiled.  critcl::reset
allows the whole critcl environment to start fresh, so "baz" can be compiled and run.
My test case seems to work just fine.

 

    Note, this is only for the compile & run mode, right ?
    Because when the file is precompiled with the critcl app ...

 
 

Yes, I'm specifically targeting compile and run mode.  I don't see how this would affect
the critcl app at all as the app would never need to invoke critcl::reset.

 

    Actually, I think that might not be possible at the moment because the
    invokation of foo, bar in the same code defining them very likely
    break this as well. And this patch will be of no help with that.

    I.e. this type of code will definitely prevent pre-building a package
    you can use later.
    It could only be made to work for compile&run ...

    Why does your project need this interleaving of definitions and uses ?
    Would it not be simpler to segregate them ?

    > I don't want to assume that all cproc procedures are defined
    > before any particular one is invoked.

    How does work with package definition and use ?

    Is your project strongly interactive where users dynamically enter the
    definitions and uses in some type of conole window ?



I'm writing a Tcl to Java/C compiler for a slightly limited subset of Tcl.  So my critcl patch is
for the ease of use for other Tcl programmers, not necessarily for my use.  I could see
where a programmer might, 1) define a proc to be compiled 2) invoke it, and 3) later, perhaps
in another source file, define additional procs to be compiled.  Thus I'd prefer to have critcl allow
as many compilation stages as needed.   Critcl 3.1.12 will throw the "Illegal...." error without
my patch.

Tcc4tcl seems to allow this, and I plan on having that as an option anyway.  I'd like to make sure
critcl works as well, especially for better optimization that gcc can do, and to support any
architecture that tcc doesn't support.  I can always include a patched version of critcl, but I would
prefer not to have nearly duplicate code of something that already exists.

My compiler is working generally well with my Java backend for JTcl, and now I'm working on the
C/Tcl backend.  I was first aiming to compile a very limited subset of Tcl (sort of a 'asm.js' version,
if you're familiar with that project), but I've been reworking the compiler to accept more of customary Tcl.
Yes, I do know about Andres Buss's Tycl, as well as recent work by dkf and kbk :-)

**Comment by andreas-kupries** [comment]
> My test case seems to work just fine.

Ok. I guess I have to get back into the internals a bit more again ...
I can sort of see what you are thinking about.

>> Note, this is only for the compile & run mode, right ?
>> Because when the file is precompiled with the critcl app ...
>
>
>
>
> Yes, I'm specifically targeting compile and run mode.  I don't see how this
> would affect
> the critcl app at all as the app would never need to invoke critcl::reset.

Except if you are feeding it a file containing critcl::reset, and
interleaved definition and uses.
That is what I was worrying about.
With the explicit targeting of compile & run I am more comfortable
with this change.
Especially if I also find a way to still have the app recognize and
abort with an error if it is fed a non-interactive input which does
this interleaving.

Note that I am currently also thinking that it might be better to do
away with exposing critcl::reset and have it automatically called in
the place where critcl normals throws the error about "definition
after compile".

That would also get rid of the failure-case where the user forgets to
run critcl::reset too.

**Comment by andreas-kupries** [comment]
That would also get rid of the failure-case where the user forgets to
    run critcl::reset too.



Yes, definitely something that I was thinking about also, I just didn't know all of the
places in critcl.tcl that I'd have to add the reset.

**Comment by andreas-kupries** [comment]
I will have to experiment in a side-branch, I believe.

**Comment by andreas-kupries** [comment]
Alternate idea to explore:
  1. Disable "dict unset v::code($file) config" (end of proc critcl::cbuild)
  1. Disable "dict set v::code($file) result closed mark" (same proc, middle)

The first means that collected information is not thrown away for the file.
The second means the file not considered "closed" after cbuild has run, preventing "AbortWhenCalledAfterBuild" from triggering.

Together they might allow a simple rebuild after extending the definitions and then using any of the new commands.

Making this conditional on file == "" could restrict this to interactive mode.
If we wish to allow this for the whole of "compile & run", where a file might be sourced multiple times, with edits in between more work might be required. Like putting in calls to empty commands as hooks and then have the critcl app redefine these hooks to activate the strict mode forbidding define after compile, for its pre-building mode.

In that case the system would never have an explicit reset in compile & run mode, only incrementally accumulating definitions with rebuilds as needed.

Thinking more ... The case as explained is about "adding" more definitions, i.e. new procs and commands. Do you also have the case of "changing" existing definitions ? That looks to be nastier to support.

**Comment by tpoindex** [comment]
On Tue, Feb 17, 2015 at 4:05 PM, Andreas Kupries
<notifications@github.com> wrote:

>
> Thinking more ... The case as explained is about "adding" more definitions, i.e. new procs and commands. Do you also have the case of "changing" existing definitions ? That looks to be nastier to support.
>



No, I don't need to redefine existing compiled proc's.

**Comment by andreas-kupries** [comment]
Ok. That should be easier then.

Note: I am putting this on a 3.1.14 milestone now, with a 3.1.13 release forthcoming, without any changes.
(I need that release for the [cf-noaa-tcl](https://github.com/ActiveState/cf-noaa-tcl) and I do not see myself fast enough in getting this issue done to be able to wait)

**Comment by tpoindex** [comment]
patch for version 3.1.13:

```
*** critcl-3.1.13/lib/critcl/critcl.tcl 2015-02-23 22:01:20.000000000 -0700
--- critcl-3.1.13-reset/lib/critcl/critcl.tcl   2015-03-23 20:55:27.023420847 -0600
***************
*** 4916,4925 ****
--- 4916,4968 ----
      return
  }

+ proc ::critcl::InitialState {} {
+     variable _initialState
+     foreach _ns [concat [namespace current] [namespace children]] {
+         dict set _initialState $_ns [namespace eval $_ns {
+             set _arrays []
+             set _vars []
+             foreach _v [lsort [info vars]] {
+                 if {[regexp {^(_)|(arg)|(auto_)|(env)|(errorInfo)|(tcl_)|(history).*} $_v]} {
+                     continue
+                 }
+                 if {[array exists $_v]} {
+                     if {[catch {lappend _arrays $_v [array get $_v]}]} {
+                         lappend _arrays $_v {}
+                     }
+                 } else {
+                     if {[catch {lappend _vars   $_v [set $_v]}]} {
+                         lappend _vars $_v {}
+                     }
+                 }
+             }
+             list arrays $_arrays vars $_vars
+         }]
+     }
+     rename ::critcl::InitialState {}
+     return
+ }
+
+ proc ::critcl::reset {} {
+     variable _initialState
+     foreach ns [concat [namespace current] [namespace children]] {
+         lassign [dict get $_initialState $ns] arrays arraydata vars vardata
+         foreach {_v _d} $arraydata {
+             unset ${ns}::$_v
+             array set ${ns}::$_v $_d
+         }
+         foreach {_v _d} $vardata {
+             set ${ns}::$_v $_d
+         }
+     }
+     return
+ }
+
  # # ## ### ##### ######## ############# #####################
  ## State

  namespace eval ::critcl {
+     variable _initialState ;# state of package arrays/variables after initialization
      variable mydir    ;# Path of the critcl package directory.
      variable run      ;# interpreter to run commands, eval when, etc

***************
*** 5088,5093 ****
--- 5131,5137 ----

        variable code            ;# This array collects all code snippets and
                                  # data about them.
+       array set  code {}

        # Keys for 'code' (above) and their contents:
        #
***************
*** 5275,5278 ****
--- 5319,5323 ----
  ## Ready

  ::critcl::Initialize
+ ::critcl::InitialState
  return

```

**Comment by andreas-kupries** [comment]
(Branch: issue-48)
commit 8e03496ca5d15ff5b388e7fd2cf4eeec542c54b7
    Added notes on the scenario to support, and issues with proposed solution.

Tom, please read of these notes to confirm/deny if my (summarized) understanding of what we wish to accomplish is correct.

**Comment by andreas-kupries** [comment]
commit 6fb6a6afa63d04cd4d2349d216924c31c6067f51
    Extended notes. Added test files for scenarios. Basic action plan.

**Comment by tpoindex** [comment]
Hi Andreas,
The scenario in 8e03496 seems a bit complicated,  this test case is what I have in mind:

```
package require critcl
critcl::clean_cache

proc critcl-define {name args type body} {
    critcl::cproc $name $args $type $body
    critcl::load
    critcl::clean_cache
    # if critcl has 'reset', no error will be rasied and all cprocs are compiled and define
    catch {critcl::reset}
}

set defs {
    hello       {char* s}       char*   {return s;}     \
    twice       {int x}         int     {return x*2;}   \
}

# in actual code, 'critcl-define' may be called from other procs
foreach {name args type body} $defs {
    critcl-define $name $args $type $body
}

puts [hello world]
puts [twice 10]
exit
```

(My project that needs 'criticl::reset' uses ccode and  ccommand instead of cproc, but that shouldn't matter.)

Also restating, that I have no requirement to redefine or recompile code that has already been compiled and defined as a command in the interpreter, nor do I intend to have critcl even seen any cproc or ccommand that has already been compiled.

**Comment by andreas-kupries** [comment]
Ok. I played around with your example, and have come to the following change

```
    # Clear existing build results for the file, make way for new declarations.
    set fx [This]
    if {[info exists v::code($fx)] &&
	[dict exists $v::code($fx) result]} {
	dict unset v::code($fx) result
    }
    return
```

Remove your "critcl::reset", and place the above into the definition of "critcl::AbortWhenCalledAfterBuild", before the existing proc body. Or replacing it entirely.

That should also do what you want. Basically, when a new declaration is made for a file FOO, all existing build data (key "result") in FOO's state dict is dropped, paving the way for the next build and its data. The input data, i.e. the previous declarations, were already removed at the very end of "critcl::cbuild". We cannot remove the result data at that point, because in mode "precompile" the outer application will still access that information to collect everything for the whole library it is building. Thus, the delay in destruction until the first new declaration. The second and further new decls will not see any result data to destroy and thus be a no-op, until a build has actually happened again.

If this indeed works for you then the only thing I still have to do is to make this conditional on the operating mode. I.e. new code above active for mode "compile & run", and the old code active for mode "precompile".

For this I plan to rename "AbortWhenCalledAfterBuild" to "HandleDeclAfterBuild, then make the new code the default implementation, and the app-critcl package will override this hook with the old implementation.

**Comment by tpoindex** [comment]
This works for me. 

 Will code that uses this function need to call it explicitly, or will this be called internally to reset state?

**Comment by andreas-kupries** [comment]
Working - Good.
Usage - This is wholly internal and automatic.

**Comment by andreas-kupries** [comment]
Will merge the branch ASAP.

**Comment by andreas-kupries** [comment]
commit b467f31e5082de49d37fcc42d68f3c16e60edacf
Merge: 4863fe1 9ea7dff
Author: Andreas Kupries <akupries@shaw.ca>
Date:   Tue May 5 22:58:13 2015 -0700

    Merge branch 'issue-48'
