### ISSUE TITLE
Parameter inconsistency

### ISSUE THREAD

**Issue by uu1101** [andreas-kupries/critcl#50]
The interpreter argument is sometimes named `ip`, other times `interp`. For example, the whole `::critcl::class` module uses `interp`, but `::critcl::cinit` makes `ip` available.  The latter is not documented.

In my opinion, critcl should use a homogeneous naming convention when the parameter names are not configurable by the user (as is the case with `::critcl::ccommand`, for example).

**Comment by andreas-kupries** [comment]
I have switched the code context for cinit fragments to now use "interp" as the variable name.
While the old name ("ip") was not documented and therefore strictly seen not public I decided to be nice. That name will still be available for the next 2 releases before I remove it. That should give everybody time to switch their code.

The name "interp" is now documented and thus part of Critcl's public API.

**Comment by uu1101** [comment]
It looks fine, thank you!
