### ISSUE TITLE
DESTDIR emulation on install

### ISSUE THREAD

**Issue by lupylucke** [andreas-kupries/critcl#76]
I was trying to create a critcl package for my linux distro. Problem is, the 'build.tcl' script does not provide support for something similar to the DESTDIR variable that usually can be used with 'make install'. 

If you're not familiar with creation of packages for linux distros, it usually goes like this:
1) build the software
2) install the software to a local directory (the DESTDIR variable).
3) create the package from the (locally) installed files
4) install package system-wide with the distro's package manager

Unfortunately, calling the critcl build/install script with a destination that anything that is not in the default ${auto_path}, will not work - unless critcl is already installed, that is:
`$ tclsh build.tcl install /home/ufu/critcl/usr/lib/tcl8.6/`

> [...]
Installed  package:      /home/ufu/critcl/usr/lib/tcl8.6/stubs_writer1
Installed application:  /home/ufu/critcl/usr/bin/critcl
can't find package critcl::app
    while executing
"package require critcl::app"
    (file "/home/ufu/critcl/usr/bin/critcl" line 4)
child process exited abnormally
    while executing
"exec >@ stdout 2>@ stderr /home/ufu/critcl/usr/bin/critcl -libdir /home/ufu/critcl/usr/lib/tcl8.6/tmp -pkg /home/ufu/..."
    ("eval" body line 1)
    invoked from within
"eval $cmd"
    invoked from within
"_install /home/ufu/critcl/usr/lib/tcl8.6"
    ("eval" body line 1)
    invoked from within
"eval _$argv"

The attached patch changes the build.tcl sript in order to make it possible to:
1) install to a destination that's not listed in $auto_path
2) use the installed files for a package to be installed system-wide (in the "standard" places) with everything still working
[destdir.patch.txt](https://github.com/andreas-kupries/critcl/files/736893/destdir.patch.txt)

**Comment by andreas-kupries** [comment]
Oh. I suspect that I introduced this with the 3.1.16 release when I had use the installed `critcl` to build the C part of it, i.e. `critcl::md5`.

Thank you for reporting this, and for making a patch.

I will get to this ASAP (which can be delayed because I am bit sick and my motivation for dev work is a bit shot right now)

**Comment by andreas-kupries** [comment]
Finally applied this, with some modifications to keep it usable with Tcl 8.4.
See https://github.com/andreas-kupries/critcl/pull/79

Please review and check that it still fixes the issue for you.
It seems to be working for me.

Although in my case the `reldstl` coming out of `dstlfromlib` is the empty list.
I might modify the app generation code to drop the entire `set libpath [file join $libpath {@path@}]` statement when that is the case.

**Comment by andreas-kupries** [comment]
No response, interpreted as agreement / no objections. Merged https://github.com/andreas-kupries/critcl/pull/79 now, branch deleted. Closing the issue.
