### ISSUE TITLE
Install on Mac OSX

### ISSUE THREAD

**Issue by sheinb** [andreas-kupries/critcl#84]
Any pointers for getting critcl installed on Mac OSX 10.13.3 with XCode command line tools in place?  I get the following: 

...
Installed package:      /usr/local/lib/tcl8.6/stubs_reader1
Installed package:      /usr/local/lib/tcl8.6/stubs_writer1
Installed application:  /usr/local/bin/critcl
expected version number but got ""
    while executing
"package vcompare $ver 10.4"
    ("foreach" body line 3)
    invoked from within
"foreach dir [glob -nocomplain -tails  -directory $base/SDKs MacOSX*] {
            set ver [string trimright  [file rootname [string range $dir $pos e..."
    invoked from within
"if {[string match macosx-* $platform]} {
    if {[info exists ::env(SDKROOT)] && $::env(SDKROOT) ne ""} {
        set SDKROOT $::env(SDKROOT)
    } el..."
    invoked from within
"interp eval $run $line"
    (procedure "readconfig" line 84)
    invoked from within
"readconfig [file join $mydir Config]"
    (procedure "::critcl::Initialize" line 39)
    invoked from within
"::critcl::Initialize"
    (file "/usr/local/lib/tcl8.6/critcl3.1.17/critcl.tcl" line 5924)
    invoked from within
"source /usr/local/lib/tcl8.6/critcl3.1.17/critcl.tcl"
    ("package ifneeded critcl 3.1.17" script)
    invoked from within
"package require critcl"
    (file "/usr/local/lib/tcl8.6/critcl-app3.1.17/critcl.tcl" line 22)
    invoked from within
...

I have set the SDKROOT environment variable (but have never seemed to need it before?) but that doesn't seem to work.

Thanks for any pointers!

**Comment by andreas-kupries** [comment]
Merged. Done.
